name: Push Tag

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - stg

jobs:
  add-tag:
    name: Add tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add git tag
        run: |
          tag="${{ github.event.inputs.env }}-$(date +%Y%m%d-%H%M%S)"
          git tag $tag
          echo Tag name: $tag

      - name: Push tag
        uses: ad-m/github-push-action@master
        with:
          tags: true
