name: Push Tag

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  add-tag:
    name: Add tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Switch to a specific branch
      #   run: |
      #     git checkout <branch_name>

      - name: Add git tag
        run: |
          tag_name=$(date +'%Y%m%d%H%M%S')
          git tag $tag_name

      - name: Push the tag to the origin
        run: |
          git push origin $tag_name
