name: Push Tag

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - staging

jobs:
  add-tag:
    name: Add tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Switch to a specific branch
      #   run: |
      #     git checkout <branch_name>

      - name: Add git tag
        run: |
          tag_name="${{ github.event.inputs.env }}-$(date +%Y%m%d-%H%M)"
          git tag $tag_name
          echo Tag name: $tag_name

      - name: Push the tag to the origin
        run: |
          git push origin $tag_name
