name: Deploy on PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Check if the event is triggered by a PR comment and the comment contains 'deploy-this-pr'
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'deploy-this-pr') }}

    steps:
      - name: Retrieve the git ref of the PR
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: Checkout code on PR branch
        uses: actions/checkout@v4
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Set timezone to Asia/Tokyo
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'Asia/Tokyo'

      - name: Add git tag with the format dev-YYYYMMDD-HHMMSS
        run: |
          tag="dev-$(date +%Y%m%d-%H%M%S)"
          git tag $tag
          echo Tag name: $tag

      - name: Push tag to GitHub
        uses: ad-m/github-push-action@master
        with:
          tags: true
          branch: ${{ steps.comment-branch.outputs.head_ref }}
